/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package multiagent;
//import static com.sun.org.apache.xerces.internal.impl.XMLScanner.NameType.DOCTYPE;
import java.sql.Connection;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.Desktop;
import java.awt.Font;
import java.awt.Frame;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.datatransfer.Clipboard;
import java.awt.datatransfer.DataFlavor;
import java.awt.datatransfer.StringSelection;
import java.awt.datatransfer.Transferable;
import java.awt.event.WindowEvent;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;
import java.io.OutputStreamWriter;
import java.io.UnsupportedEncodingException;
import java.nio.charset.StandardCharsets;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Stack;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.servlet.ServletException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import javax.swing.JProgressBar;
import javax.swing.JTextArea;
import javax.swing.UIManager;
import javax.swing.undo.UndoManager;
import masmt.*;
import static multiagent.SinhalaWord.list;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditEvent;
import javax.swing.event.UndoableEditListener;
import javax.swing.undo.CannotRedoException;
import javax.swing.undo.CannotUndoException;
import javax.swing.undo.UndoManager;
import static org.jdom2.filter.ContentFilter.DOCTYPE;
public class NewGui extends javax.swing.JFrame {

    ManagerAgent obj = new ManagerAgent();
 
Connection conn=null;
     PreparedStatement pstmt;
    ResultSet rs=null;
    public NewGui() {
        initComponents();
        
        obj.start();
    
    }

pbThread t1;
class pbThread extends Thread{
JProgressBar pbar;
pbThread (JProgressBar pbar){
pbar= lordbar;
}
public void run(){
int min=0;
int max=20; 
lordbar.setMinimum(min);
lordbar.setMaximum(max);
lordbar.setValue(0);

UIManager.put("lordbar.selectionBackground",Color.BLUE);
for (int i=min; i<=max; i++){
lordbar.setValue(i);
try {
sleep(100);
} catch (InterruptedException ex) {
Logger.getLogger(NewGui.class.getName()).log(Level.SEVERE, null, ex);
}
}
}
}


    /**
     * This method is called from within the constructor to initialize the form. 
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    //close window
    public void close()
    {
        WindowEvent close=new WindowEvent(this,WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(close);
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDialog1 = new javax.swing.JDialog();
        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        copy = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        redo = new javax.swing.JButton();
        clear = new javax.swing.JButton();
        undo = new javax.swing.JButton();
        AddDatabase = new javax.swing.JButton();
        Autopaste = new javax.swing.JButton();
        lordbar = new javax.swing.JProgressBar();
        jScrollPane1 = new javax.swing.JScrollPane();
        output = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jLabel1 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("අකුර සිංහල වචන පිරික්සුම");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jLabel3.setText("අක්ෂර වින්‍යාසය අනුව වැරදි වචන");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 540, -1, -1));

        jLabel2.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jLabel2.setText("ඔබේ පෙළ මෙහි ලියන්න");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, -1, -1));

        jButton2.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton2.setToolTipText("Click Here for Additional Details");
        jButton2.setText("වැඩි විස්තර ");
        jButton2.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 480, 120, 40));

        jButton1.setFont(new java.awt.Font("Iskoola Pota", 1, 18)); // NOI18N
        jButton1.setToolTipText("Click Here to Check the Text");
        jButton1.setText("පිරික්සන්න");
        jButton1.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 153, 153)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, 120, 40));

        copy.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiagent/1.png"))); // NOI18N
        copy.setToolTipText("Copy");
        copy.setAlignmentY(0.0F);
        copy.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(255, 255, 255)));
        copy.setBorderPainted(false);
        copy.setFocusable(false);
        copy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                copyActionPerformed(evt);
            }
        });
        jPanel1.add(copy, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 350, 60, 60));

        exit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiagent/ICONS (7).png"))); // NOI18N
        exit.setToolTipText("Close the Window");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });
        jPanel1.add(exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 200, 60, 60));

        redo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiagent/ICONS (5).png"))); // NOI18N
        redo.setToolTipText("Redo");
        redo.setAlignmentX(0.5F);
        redo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redoActionPerformed(evt);
            }
        });
        jPanel1.add(redo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 590, 60, 60));

        clear.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiagent/5.png"))); // NOI18N
        clear .setToolTipText("Clean");
        clear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearActionPerformed(evt);
            }
        });
        jPanel1.add(clear, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 430, 60, 60));

        undo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiagent/3.png"))); // NOI18N
        undo.setToolTipText("Undo");
        undo.setAlignmentX(0.5F);
        undo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoActionPerformed(evt);
            }
        });
        jPanel1.add(undo, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 510, 60, 60));

        AddDatabase.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiagent/ICONS (8).png"))); // NOI18N
        AddDatabase.setToolTipText("Add to Database");
        AddDatabase.setBorderPainted(false);
        AddDatabase.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddDatabaseActionPerformed(evt);
            }
        });
        jPanel1.add(AddDatabase, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 670, 60, 60));

        Autopaste.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiagent/2.png"))); // NOI18N
        Autopaste .setToolTipText("Paste");
        Autopaste.setBorderPainted(false);
        Autopaste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AutopasteActionPerformed(evt);
            }
        });
        jPanel1.add(Autopaste, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 270, 60, 60));

        lordbar.setBackground(new java.awt.Color(0, 255, 255));
        lordbar.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 1, 1, new java.awt.Color(0, 51, 51)));
        jPanel1.add(lordbar, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 720, 900, 30));

        jScrollPane1.setBackground(new java.awt.Color(255, 255, 255));

        output.setColumns(20);
        output.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        output.setLineWrap(true);
        output.setRows(5);
        output.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane1.setViewportView(output);
        output.setEditable(false);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 580, 900, 130));

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        jTextArea2.setColumns(20);
        jTextArea2.setFont(new java.awt.Font("Iskoola Pota", 0, 24)); // NOI18N
        jTextArea2.setLineWrap(true);
        jTextArea2.setRows(5);
        jTextArea2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jScrollPane2.setViewportView(jTextArea2);
        jTextArea2.getDocument().addUndoableEditListener(
            new UndoableEditListener() {
                @Override
                public void undoableEditHappened(UndoableEditEvent e) {
                    manager.addEdit(e.getEdit());
                }
            }
        );

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 240, 900, 220));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/multiagent/background.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1020, 770));

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String Text=jTextArea2.getText().replaceAll("[a-z]|[A-Z]|[0-9]","");
        if("".equals(Text))
        {
            JOptionPane.showMessageDialog(null, "Please  Insert Text");
        }
        else
        {
                jTextArea2.setText(Text);
        obj.StartChecking(Text);
        
         t1 = new pbThread(lordbar);
t1.start();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed

        close(); 

    }//GEN-LAST:event_exitActionPerformed

    private void AutopasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AutopasteActionPerformed
        String ret = "";
Clipboard sysClip = Toolkit.getDefaultToolkit().getSystemClipboard();



Transferable clipTf = sysClip.getContents(null);



if (clipTf != null) {



if (clipTf.isDataFlavorSupported(DataFlavor.stringFlavor)) {
try {
ret = (String) clipTf
.getTransferData(DataFlavor.stringFlavor);
} catch (Exception e) {
e.printStackTrace();
}
}
}
jTextArea2.setText(ret);
 
    }//GEN-LAST:event_AutopasteActionPerformed

    private void redoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redoActionPerformed
try {
if (manager.canRedo()) {
manager.redo();
}
} catch (CannotRedoException e) {
throw new RuntimeException(e);
}
    }//GEN-LAST:event_redoActionPerformed

    private void copyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_copyActionPerformed
      String myString = output.getText();
        StringSelection stringSelection = new StringSelection(myString);
        Clipboard clipboard = Toolkit.getDefaultToolkit().getSystemClipboard();
        clipboard.setContents(stringSelection, null);
        JOptionPane.showMessageDialog(null, "You Have Copied the checked data");
    }//GEN-LAST:event_copyActionPerformed
    UndoManager manager=new UndoManager();
    private void undoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoActionPerformed
try {
if (manager.canUndo()) {
manager.undo();
}
} catch (CannotUndoException e) {
throw new RuntimeException(e);
} 

    }//GEN-LAST:event_undoActionPerformed
private void jTextArea2FocusLost(java.awt.event.FocusEvent evt) {
// TODO add your handling code here:
if(jTextArea2.getText().equals("")){
jTextArea2.setText("ඔබේ පෙළ මෙහි ලියන්න");
}
}
private void jTextArea2FocusGained(java.awt.event.FocusEvent evt) {
// TODO add your handling code here:
if(jTextArea2.getText().equals("ඔබේ පෙළ මෙහි ලියන්න")){
jTextArea2.setText("");
}
}
    private void clearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearActionPerformed
        jTextArea2.setText("");
        output.setText("");
    }//GEN-LAST:event_clearActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     output();
      Write_The_TextArea();
    }//GEN-LAST:event_jButton2ActionPerformed

    @SuppressWarnings("empty-statement")
    private void AddDatabaseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddDatabaseActionPerformed
 
   //int _id = 0;
 
        String sql = "INSERT INTO sinhala(word) VALUES(?)"; 
        try (Connection  conn=Add_to_Database.ConnectDb();
                PreparedStatement pstmt = conn.prepareStatement(sql)) {
    // int id=52463+i;
            System.out.println();
         for(int i=0;i<SinhalaWord.getListcount();i++)
 {
            //  pstmt.setInt(1, id);
          if(list[i].getStatus()==2)
                  {
            pstmt.setString(1,list[i].getWord());
                  }
            pstmt.executeUpdate();
                   
 }
             } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Can't Insert the data");
        }
    
    }//GEN-LAST:event_AddDatabaseActionPerformed
  public void output()
{
 //  JTextArea kk = new JTextArea();
    String html="<div class=\"container\">\n" +
"                    <div class=\"row mt22\">\n" +
"            <div class=\"my_span9\">\n" +
"                      <div class=\"box_shade p13 successdiv\" style=\"display:none;\"></div>\n" +
"        <form name=\"checkform\" id=\"checkform\" spellcheck=\"false\" action=\"https://community.languagetool.org/\" method=\"POST\">\n" +
"		<input type=\"hidden\" name=\"type\" value=\"1\">\n" +
"        <div>\n" +
"          <div class=\"box_shade p13\">\n" +
"            <p>" ;
    for(int j=0;j<SinhalaWord.getListcount();j++)
          {
 
             if(list[j].getStatus()==2)
             {
            
              
              html=html+" "+"<span style=\"color:#00D590\">"+list[j].getWord();
                
             }
              if(list[j].getStatus()==1)
             {
               html=html+" "+"<span style=\"color:#0083EC\">"+list[j].getWord();
             }
              if(list[j].getStatus()==0)
              {
                html=html+" "+"<span style=\"color:#B00000 \">"+list[j].getWord();

              }
          }
             html=html+"</p></div>\n<tbody>\n" +
"<tr>\n" +
"<td style=\"font-size:4px; background-color: white\">\n" +
"<img src=\"C:\\Users\\HASHINI\\Pictures\\MultiAgent\\src\\multiagent/red.png\" width=\"10px\" height=\"10px\" alt=\"Red\"> <span style=\"color:red\">වැරදි</span> &nbsp;&nbsp;\n" +
"<img src=\"C:\\Users\\HASHINI\\Pictures\\MultiAgent\\src\\multiagent/green.png\" width=\"10px\" height=\"10px\" alt=\"Green\"><span style=\"color:green\"> නිවැරදි </span> &nbsp;&nbsp;\n" +
"<img src=\"C:\\Users\\HASHINI\\Pictures\\MultiAgent\\src\\multiagent/blue.png\" width=\"10px\" height=\"10px\" alt=\"Blue\"><span style=\"color:blue\"> අවිනිශ්චිත </span>\n" +
"</td>\n" +
"</tr>\n" +
"</tbody>" +
"</div>\n" +
"        <div class=\"row\"> </div></form><h2>උදාහරණ වාක්‍යයන් සදහා වචනය මත Click කරන්න</h2><br>";
            
      for(int j=0;j<SinhalaWord.getListcount();j++)
          {
       String html2=null;
             WebAgent wa=new WebAgent();
            try {
                     html2= wa.getUrlForSearch(list[j].getWord());
                                   html=html+" ";

                 } catch (Exception ex) {
                     System.out.println("Error");
                 }
          html=html+html2;      
          }
              File f = new File("source.htm");
        BufferedWriter bw = null;
        try {
           FileOutputStream fos = new FileOutputStream(f);
       OutputStreamWriter osw = new OutputStreamWriter(fos, StandardCharsets.UTF_8);
       bw = new BufferedWriter(osw);
        } catch (IOException ex) {
            Logger.getLogger(NewGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bw.write("<html lang=\"en\"><head>\n" +
"<title>Akura Sinhala Spell Checker</title>\n<link rel=\"icon\" href=\"C:\\Users\\HASHINI\\Pictures\\MultiAgent\\src\\multiagent/logo1.png\" type=\"image/x-icon\">" +
"<link rel=\"stylesheet\" href=\"C:\\Users\\HASHINI\\Pictures\\MultiAgent\\src\\multiagent/441bc80.css\">\n" +
"</head>\n" +
"<body data-new-gr-c-s-check-loaded=\"14.1034.0\" data-gr-ext-installed=\"\" data-new-gr-c-s-loaded=\"14.1034.0\">\n" +
"<div class=\"navbar navbar-inverse navbar-static-top\"> </div>\n" +
"<div>\n" +
"        <div class=\"relative headerpulllft\">\n" +
"    <div class=\"headerheight\">\n" +
"      <div class=\"headerbanner\">\n" +
"        <div class=\"container\">\n" +
"          <div class=\"pt26\">\n" +
"            <div id=\"myCarousel\" class=\"carousel slide\">\n" +
"              <!-- Carousel items -->\n" +
"              <div class=\"carousel-inner\">\n" +
"                <div class=\"active item\">\n" +
"                  <div class=\"row\">\n" +
"                    <div class=\"span7 mt20\">\n" +
"                      <div class=\"pl30\">\n" +
"                        <div class=\"carousel-text\"><p style=\"font-size:30px\">Akura Sinhala Spell Checker<br>ඔබ ඇතුලත් කල වචන වලට අදාලව ප්‍රතිඵල</p></div>\n" +
"                        </div>\n" +
"                    </div>\n" +
"                    <div class=\"span5 headerimg\"><img src=\"C:\\Users\\HASHINI\\Pictures\\MultiAgent\\src\\multiagent/logo1.png\" width=\"300\" height=\"250\" alt=\"\"></div>\n" +
"                       </div>\n" +
"                </div>\n" +
"</div>\n" +
"              <!-- Carousel nav -->\n" +
"              </div>\n" +
"          </div>\n" +
"        </div>\n" +
"      </div>\n" +
"</div>\n" +
"  </div></div>\n" +
"</div>\n" +
"</body></html>");
        } catch (IOException ex) {
            Logger.getLogger(NewGui.class.getName()).log(Level.SEVERE, null, ex);
        }
         try {
            bw.write(html);
        } catch (IOException ex) {
            Logger.getLogger(NewGui.class.getName()).log(Level.SEVERE, null, ex);
        }
        try {
            bw.close();
        } catch (IOException ex) {
            Logger.getLogger(NewGui.class.getName()).log(Level.SEVERE, null, ex);
        }

        try {
            Desktop.getDesktop().browse(f.toURI());
        } catch (IOException ex) {
            Logger.getLogger(NewGui.class.getName()).log(Level.SEVERE, null, ex);
        }
    
             
          
          
}
  public void Write_The_TextArea()
  {
        
        
        output.setForeground(Color.BLUE);
      for(int j=0;j<SinhalaWord.getListcount();j++)
          {
           
           //String html2="<div><h1>Hello gg </h1><div>";
              
              if(list[j].getGrammar_Status()==1)
              {
               output.append("\n"+list[j].getWord());
              }
          }
  }

    /**
     * @param args the command line arguments
     */
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewGui().setVisible(true);
               
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddDatabase;
    private javax.swing.JButton Autopaste;
    private javax.swing.JButton clear;
    private javax.swing.JButton copy;
    private javax.swing.JButton exit;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea2;
    public static javax.swing.JProgressBar lordbar;
    public javax.swing.JTextArea output;
    private javax.swing.JButton redo;
    private javax.swing.JButton undo;
    // End of variables declaration//GEN-END:variables
}
